### ISSUE TITLE
estraverse-fb dependency

### ISSUE THREAD

**Issue by bel0v** [rogic89/ToDo-react-redux-immutable#1]
please add `estraverse-fb` to `package.json`

**Comment by crathermel** [comment]
@FoxWhite @rogic89 What version should be added in the current repo to get it to build ?  

When I run `npm install estraverse-fb --save` it complains about peer dependancies.  

``````
npm ERR! peerinvalid The package eslint@2.9.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer eslint-config-airbnb@6.2.0 wants eslint@^2.4.0
npm ERR! peerinvalid Peer eslint-loader@1.3.0 wants eslint@>=1.6.0 <3.0.0
npm ERR! peerinvalid Peer babel-eslint@5.0.4 wants eslint@<2.3.0```
``````

**Comment by rogic89** [comment]
Thank for info, I shrink-wrapped the npm packages and now it works as intended.
