### ISSUE TITLE
ERROR in ./src/init.js

### ISSUE THREAD

**Issue by timmeade** [rogic89/ToDo-react-redux-immutable#3]
npm init

npm start

Fails 

ERROR in ./src/init.js
Module build failed: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)

**Comment by pennywong** [comment]
the same error, any solution?

**Comment by rogic89** [comment]
Hey, the problem is with new node version. Downgrading it will solve the problem

**Comment by avastamin** [comment]
Why don't you fix the problem with latest node version??

**Comment by rogic89** [comment]
Updated babel-core and babel-eslint and now it working fine.
